global:
  scrape_interval:     5s
  evaluation_interval: 5s

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: prometheus 
    metrics_path: /v1/metrics
    static_configs:
      - targets: ['web:5005']

